//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDetail
    {
        public int ID { get; set; }
        public string selector { get; set; }
        public string foodTitle { get; set; }
        public string foodDescription { get; set; }
        public string foodPhoto { get; set; }
    }
}
